# Generated by Django 5.2.11 on 2026-05-08 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
        ('vendors', '0002_vendorprofile_commission_rate_storeextensionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorsubscription',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendorprofile'),
        ),
    ]
